### ISSUE TITLE
中文版

### ISSUE THREAD

**Issue by bobzhang** [liuxinyu95/AlgoXY#1]
其实你这本书内容还不错，为什么不把他写成中文呢？(不要误会我的意思，我英文水平还行)

**Comment by liuxinyu95** [comment]
非常感谢comment！
事实上，有不少朋友都建议我写中文版。我也非常希望这本书有中文版，这样能帮助很多使用中文的读者。
一直坚持用英文写了4年的最大原因是：“时间紧迫”。

这本书是我利用纯业余时间写的，它的绝大部分内容（超过99%）都和我的工作无关。
我每次抽时间写的时候，都用一种争分夺秒的感觉。虽然4年时间完成了不少，但是未完成的部分还很多（截至今天）：
- 基本搜索算法，DFS, BFS；
- 字符串搜索算法，KMP, BM
- 动态规划；
- 增加更多趣题，主要是ACM/ICPC上的解析
- 重写Trie/Patricia, BTree, Binary Heap等章节，使得和整体的写作风格一致

除了内容上的，还有这些计划：
- 提供Erlang, OCaml, Scala这些语言的例子；
- 提供更多Imperative语言的例子
- 提供另外一些编程范式语言，如prolog的例子

这些现实都决定了AlgoXY一书，在未来相当长的时间内，内容仍然是不断变化的。所以我很难同时维护两门以上语言的版本。例如中文版+英文版。这就决定了我必须选择一门语言，并且在全书第一次脱稿前专注在上面。

经过仔细权衡，我还是选择了英文，原因如下：
1. 如果英文版得到了读者的认可，必然会有热心读者将其翻译成其他语言，包括中文；
2. 即使中文版得到了读者的认可，被翻译成其他语言的机会仍然较小（就目前的统计情况看）；
3. 我参考的大部分资料，尤其是函数式算法和数据结构的资料都是英文的，
4. 英文版屏蔽了很多噪声，可以使我专心写作，这就如同Haskell社区的那个slogan: avoid success at any cost.

等待中文版的朋友还需要再耐心等一等，全书脱稿后，我会考虑启动中文版的翻译工作。

谢谢大家理解！

**Comment by bobzhang** [comment]
两点反馈：
1. 本书的主要受众应该还是中文读者，英文里面好的算法书琳琅满目，像purely functional data structure, peals of functional algorithm design 很多原创的书籍.
2. latex真不是什么好东西，我从大二开始用，现在已经有5,6年了，用的越多，越对之深恶痛绝，无数时间浪费
在了这种工具上。
挺敬佩你的耐力的，加油！

**Comment by mountain** [comment]
钦佩！加油！相信不少人在关注这个项目！

**Comment by rainoftime** [comment]
我可以先试着翻译几篇

**Comment by liuxinyu95** [comment]
非常感谢！
可以随时branch出中文的分支。
我以前曾经提供过common.tex里面有cjk的支持，只要把所有的common-en的引用换位common就可以直接用中文了。你可以查以前的git history。

翻译中有任何疑问可以随时联系我。

**Comment by QingYun** [comment]
今天刚发现这本书, 还没读. 同为95年的, 先跪拜您的英语水平.

**Comment by princemaple** [comment]
你好, 今天刚发现这本书, 发现比introduction to algorithms更让我看得进

感谢编写此书, 并且希望此书能最终实现预期的目标

**Comment by princemaple** [comment]
之前并未发现此书已经v1 release. 恭喜!

**Comment by liuxinyu95** [comment]
创建了一个用于中文版翻译的分之zh-cn
https://github.com/liuxinyu95/AlgoXY/tree/zh-cn

目前采用xelatex实现对中文的支持。翻译一章时步骤大致如下：
1，更改Makefile，将xxxx-en改为xxxx-zh-cn
2，更改main-zh-cn.tex将相应章节从xxxx-en改为xxxx-zh-cn
3，到相关章节的目录下，更改Makefile，将xxxx-en改为xxxx-zh-cn；
4，使用xelatex替换各章节Makefile中的latex。如：
before:

```
pdf: $(OBJECT).dvi
    dvipdfmx $(OBJECT)

tex: image
    latex $(OBJECT)
    latex $(OBJECT)
```

after:

```
pdf: image
    xelatex $(OBJECT)

tex: pdf
```

5，将以前的xxx-en.tex重命名为xxxx-zh-cn.tex，文件编码改为utf-8
6，将其中包含的common-en.tex，替换为common-zh-cn.tex
7，翻译相关英文为中文。

**Comment by liuxinyu95** [comment]
已经将所有章节设置为支持中文，直接打开任何一章，设置编码为utf-8，即可翻译。
