### ISSUE TITLE
排版

### ISSUE THREAD

**Issue by xin-jin** [liuxinyu95/AlgoXY#15]
请问是否能改进一下排版。这本书是以电子书形式发布的，但是排版却是印刷书的格式。譬如：1. 页边距过大，如果设为1inch左右比较好。 2. 页面是two-sided格式（奇数页往左倾，偶数页右倾），非印刷书籍这个似乎不需要。我觉得类似http://theory.stanford.edu/~tim/f13/f13.pdf 这样的格式似乎更易阅读。

**Comment by liuxinyu95** [comment]
非常感谢！我稍后提供一个非印刷格式的排版。

**Comment by liuxinyu95** [comment]
暂时关闭这个issue。我目前准备优先添加Java/Scala例子程序。
