### ISSUE TITLE
chapter 4 delta

### ISSUE THREAD

**Issue by y4h2** [liuxinyu95/AlgoXY#18]
根据4.1中平衡因子的定义，为|L| - |R|
但在4.11中平衡因子的定义为equals to the difference from the right sub tree and left sub tree, 且后面的解释都以此为准
请问是应该以哪个定义为标准？

**Comment by liuxinyu95** [comment]
多谢指出这个问题。
平衡因子主要是通过左右子树高度的插值来体现平衡性。可以定义为右减去左，也可以定义为左减去右。但是一旦定义好，应该保证前后使用一致的定义。
这一章实际上我们后面用的是右减去左，但是最开始的定义给出的左减去右，出现了不一致。这是我的错误。
我周末会修改4.1中的定义delta(T) = |R| - |L|。

再次感谢！

**Comment by liuxinyu95** [comment]
已修改，下次release时即可看到pdf上的改动。再次感谢！
希望能有更多的问题被发现。
