### ISSUE TITLE
能给kindle提供个mobi或者epub格式的么 谢谢

### ISSUE THREAD

**Issue by Insofan** [liuxinyu95/AlgoXY#20]
如题，pdf有时候不在laptop上看不方便.提供个电子书格式平时看会方便很多 ，谢谢

**Comment by ghost** [comment]
这本书是用LaTeX排版系统编写的，用`xelatex`命令编译之后输出的是pdf格式。要得到epub格式，有两种办法。
1. 用`pandoc`命令转换。但是看网上的评论，`pandoc`转换LaTeX文档的质量不是特别高。
2. 把LaTeX文档转换为HTML，再转换为epub。我没试过，不知道效果如何。

**Comment by adamcavendish** [comment]
You may try using Calibre for the convertion.

**Comment by Insofan** [comment]
Calibre sucks at converting PDF files.

**Comment by bookug** [comment]
mobipocket creator, just for windows

**Comment by liuxinyu95** [comment]
Close this issue for now, Let's see the qualified data about how many people want the epub ver.
