### ISSUE TITLE
binary堆

### ISSUE THREAD

**Issue by KiwiFlow** [liuxinyu95/AlgoXY#23]
中文版，Chapter 8，第196页。
“如果k是一个最小堆的顶部元素，所有左右子树中的元素都小于k。“ 应该是
“如果k是一个最小堆的顶部元素，所有左右子树中的元素都大于k。”

**Comment by liuxinyu95** [comment]
非常感谢，已修改到pub分支，稍后我会合并回zh-cn分支。
