### ISSUE TITLE
有关红黑树的问题

### ISSUE THREAD

**Issue by Phymin** [liuxinyu95/AlgoXY#24]
为什么没有红黑树的c++实现代码，但是书中又说有的？

**Comment by YanfeiHao** [comment]
您好，这部分代码确实没有。

xueersi138@sina.com

发件人： Phymin
发送时间： 2016-10-25 22:15
收件人： liuxinyu95/AlgoXY
主题： [liuxinyu95/AlgoXY] 有关红黑树的问题 (#24)
为什么没有红黑树的c++实现代码，但是书中又说有的？

**Comment by liuxinyu95** [comment]
红黑树是本书最早写好的一章（完成于2009年，比第一章还早）。当时提供C++例子程序时，直接使用了SGI STL中Map的源代码的大部分，因为早起的STL比较简单，也没有大量使用各种C++模板的语言特性。后来在重写全书时，我发现STL的源码已经变得很复杂，并不适合直接供读者参考。我计划等中文版修订完成后，提供一个更加易读的C++红黑树实现。这个issue我不会关，但是需要时间来完成。

**Comment by liuxinyu95** [comment]
同样的问题AVL树也有，需要补充AVL树的C/C++例子代码。

**Comment by liuxinyu95** [comment]
红黑树的C++例子代码已添加：
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/datastruct/tree/red-black-tree/src/rbt.cc
我会另开一个issue来track AVL树的C/C++例子代码。
