### ISSUE TITLE
Section 0.2.3 Figure Overlaps (Page 17 and 19)

### ISSUE THREAD

**Issue by ghost** [liuxinyu95/AlgoXY#26]
Hey,

The figure overlaps in at-least two place I can see so far:

https://github.com/liuxinyu95/AlgoXY/blob/algoxy/others/preface/preface-en.tex#L353 (Page 17)
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/others/preface/preface-en.tex#L444 (Page 19)

How can it can be corrected? I am not familiar with Tex. I don't know if the figure or content is the problem.

**Comment by liuxinyu95** [comment]
Hello,

It's caused by the margin of the figure. I fixed it just now. It will be OK in the next release. Please let me know if you need a copy of PDF.

**Comment by ghost** [comment]
Great thanks for your attention! Please do update the official PDF  in the README.md file. I will generate PDF in my machine should be fine.
