### ISSUE TITLE
Some compile error on q2.dot

### ISSUE THREAD

**Issue by syhily** [liuxinyu95/AlgoXY#28]
dot -Gsize="8,10.5" -Tps -o q2.ps q2.dot
Warning: flat edge between adjacent nodes one of which has a record shape - replace records with HTML-like labels
  Edge x1 -> x2
Error: lost x1 x2 edge
Error: lost x2 x3 edge
make[2]: *** [q2.ps] Error 1
make[1]: *** [image] Error 2

**Comment by liuxinyu95** [comment]
是Make英文版还是中文版？是在根目录下还是在others/preface下单独make？
OS是什么？dot的版本是什么？
可以如下方法查看dot版本：
[xinyul@f45c89ba9a29:~/work/algoxy/others/preface/img] $ dot -V
dot - graphviz version 2.38.0 (20140413.2041)

**Comment by syhily** [comment]
英文版，我的 dot 版本是 `dot - graphviz version 2.40.1 (20161225.0304)`
macOS 10.12，在根目录下的 make

**Comment by liuxinyu95** [comment]
我稍后upgrade到2.40.x，帮你看一下什么问题。争取这周末前回复给你。

**Comment by lsq** [comment]
@liuxinyu95 我编译也出现了同样问题，dot版本同上

**Comment by liuxinyu95** [comment]
原因是新版dot中，要用shape=none，来代替无边框的形状。
我已经提交了一个可通过编译的q2.dot到jvm分支: 
https://github.com/liuxinyu95/AlgoXY/commit/2d455b4af31e8609a6b09586a7b2792ccb68d263
周末我会统一fix掉所有分支上的这类问题。

**Comment by liuxinyu95** [comment]
algoxy分支已修复并验证；
jvm分支的修复尚未验证；
zh-cn分支尚未修复。

**Comment by liuxinyu95** [comment]
已将jvm, zh-cn分支中的内容合并到主分支。
