### ISSUE TITLE
前驱(Successor)和后继(predecessor)中的不解

### ISSUE THREAD

**Issue by hongta** [liuxinyu95/AlgoXY#29]
在 1.5.3 前驱(Successor)和后继(predecessor)

给定元素x，它的后继元素y是满足y > x的最小值。有两种情况:如果x所 在的节点有一个非空的右子树，则右子树中的最小值就是答案。如图1.5所示， 8的后继元素为9，它是元素8的右子树中的最小值。另外一种情况是，如果x没 有非空的右子树，我们需要向上回溯，找到最近的一个祖先，使得该祖先的左 侧孩子，也为x的祖先。如图1.5所示，元素2所在的节点没有右侧分支，我们向 上回溯一步找到元素1，**但是1没有左侧分支，因此需要继续向上查找**，这次我 们到达了元素3所在的节点。而3的左侧孩子，同样也是2的祖先。至此，我们找 到了2的后继元素3。

这里查找2的后继，和1的左子树有什么关系？

**Comment by liuxinyu95** [comment]
这里想说的是，当我们沿着父节点的向上回溯查找时，如果一旦发现当前节点是父节点的左子树，则查找停止，父节点就是后继节点。

因此，检查节点2的父节点，发现它是1，但是2不是1的左子树，因此需要继续向上查找。

我会打开此issue2周，如果没有进一步的问题，会关闭此issue。
