### ISSUE TITLE
Release v0.618034-zh-cn has no PDF file uploaded by now.

### ISSUE THREAD

**Issue by SnowOnion** [liuxinyu95/AlgoXY#30]
https://github.com/liuxinyu95/AlgoXY/releases

**Comment by liuxinyu95** [comment]
I intended to remove the PDF in Chinese. However, with all the LaTeX source manuscript, and build script, you can make the pdf by yourself. Please drop me an email: lliuxinyu95@gmail.com if you meet any problems.
