### ISSUE TITLE
Found some errata in published Chinese book

### ISSUE THREAD

**Issue by xiaohanyu** [liuxinyu95/AlgoXY#32]
Just read your book, it's awesome, http://www.ituring.com.cn/book/1907, first Chinese book to introduce traditional data structures and algorithms with lots of functional languages code snippets.

I found some errata:

### typo
I found a typo in Appendix, page 505. This line https://github.com/liuxinyu95/AlgoXY/blob/zh-cn/others/appendix/list/list-zh-cn.tex#L320 , in the published Chinese book, is not indent properly, which may results some confusions to the readers. 

Maybe it should be recorded in a errata. 

![img_6022](https://cloud.githubusercontent.com/assets/1164623/23576688/28be2802-00e7-11e7-88d7-fac667028208.JPG)

### code listing error

In page 548

![fullsizerender](https://cloud.githubusercontent.com/assets/1164623/23584551/ce759268-019f-11e7-9241-8e2cc2902729.jpg)

The code should be a plain code environment (aha, I know that it is a `lstlisting` environment in LaTeX), so it should not contains a `\lambda` character, and the `\rightarrow` should be plain `->` as in Haskell code.

I've also checked the LaTeX source code here https://github.com/liuxinyu95/AlgoXY/blob/algoxy/others/appendix/list/list-en.tex#L3071 and here https://github.com/liuxinyu95/AlgoXY/blob/zh-cn/others/appendix/list/list-zh-cn.tex#L2651 and found these two line are correct. So I think this should be put into some errata list.

### section title error

Page 549, the `subsubsection` title is not right, it should not start with a "4". It seems that this error has been fixed in https://github.com/liuxinyu95/AlgoXY/blob/zh-cn/others/appendix/list/list-zh-cn.tex#L2692 .

![img_6036](https://cloud.githubusercontent.com/assets/1164623/23585061/4737666e-01ae-11e7-9900-d0741f276be2.JPG)

**Comment by liuxinyu95** [comment]
Thanks a lot!
For the indent error in P505, and subsubsection error in 549, I've notified the publish house.
These errors should be corrected in the next publish (current is the 2nd publish).

For the lambda and left arrow, they were left as the Greek and math symbols because I think it looks cool :-). Some modern editor, e.g. Emacs, support displaying Haskell code in such manner.
