### ISSUE TITLE
关于红黑树的删除算法

### ISSUE THREAD

**Issue by c-hui** [liuxinyu95/AlgoXY#42]
书中是这样描述的：一个子节点为双重黑色空节点，另外一个子分支不为空，我们可以安全地将其变为普通的NIL。
这里直接删除的话，不是会使其它节点到这个NIL节点的路径中黑色节点数少一个，破坏任何红黑树的性质5了吗？
![enter image description here](https://i.imgur.com/pmoA09M.png)

**Comment by liuxinyu95** [comment]
红黑树的性质5是说：对任意节点，从它出发，到所有**叶子**节点的路径上包含相同数量的黑色节点。

如你贴在上面图所示。将这里的节点4变为双重黑色的NIL，进而变为普通NIL后，注意它已经不再是**叶子**节点了。

也就是说，所有以前通往叶子节点4的路径都消失了。拿节点3来说，删除前有3个通往叶子节点的路径：
1. 路径A: 3 -> 2 -> 1，含有2个黑色节点；
2. 路径B: 3 -> 5 -> 4,  含有2个黑色节点；
3. 路径C: 3 -> 5 -> 6,  含有2个黑色节点；

将4变为双重黑色的NIL，进而变为普通NIL，后从3通往叶子节点的路径减少了1个：
1. 路径A: 3 -> 2 -> 1，含有2个黑色节点；
3. 路径C: 3 -> 5 -> 6,  含有2个黑色节点；

因此并没有违反红黑树的性质

**Comment by c-hui** [comment]
首先，很感谢您的解答，不过还是有点疑问。书中的性质5是这样的：
>对任一节点，从它出发到所有叶子节点的路径上包含相同数量的黑色节点。

如果是考虑*叶子节点*是没有问题的，但是这样的话如果所有节点都形成一条单链，这样的话仅有一个叶子节点，也就仅有一条路径，是不是也满足性质5。

而且我看维基百科中的性质5是这样描述的：
>Every path from a given node to any of its descendant NIL nodes contains the same number of black nodes.

它说的是到后代的NIL节点，所以这里就不是很明白了。

**Comment by liuxinyu95** [comment]
多谢你提出的这个后继问题。这个问题非常好。我需要时间思考一下然后给你回复。

**Comment by liuxinyu95** [comment]
完全重写了红黑树的删除部分，修正了这个错误。
请参考附件的pdf
[rbtree-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/1359197/rbtree-zh-cn.pdf)
后继会修改其他分支以及例子程序。

**Comment by liuxinyu95** [comment]
将命令式删除部分作为附录单独描述，请参考附件的pdf
[rbt-del-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/1385252/rbt-del-zh-cn.pdf)
