### ISSUE TITLE
Can you release a new PDF?

### ISSUE THREAD

**Issue by ghost** [liuxinyu95/AlgoXY#43]
Hello @liuxinyu95 ,

Thanks for this wondefrul work. Can you please release latest version's PDF?

**Comment by ghost** [comment]
I uploaded one here https://archive.org/details/algoxy-1c79b6b-july-30-2017. Do you want to refer it somewhere in main page? Or if this is expected to compiled all the time, that is fine too.

**Comment by liuxinyu95** [comment]
Hi, 

There are two reasons why not all the PDF files are attached in the releases.
1), As we provided all the TeX and source files, PDF can be build by everybody;
2), The book in Chinese has been published.

Hope you can understand this.

Thanks.
