### ISSUE TITLE
Incorrect if statement condition in Insertion Sort Improvement 2

### ISSUE THREAD

**Issue by po2xel** [liuxinyu95/AlgoXY#44]
Hi @liuxinyu95 , 
Thanks for this open-source algorithm book. I am reading it and find an incorrect if statement condition in Insertion Sort Improvement 2.

```
\begin{algorithmic}
\Function{Insert}{$L, x$}
  \State $p \gets$ NIL
  \State $H \gets L$
  \While{$L \neq$ NIL $\land $ \Call{Key}{$L$} $<$ \Call{Key}{$x$}}
    \State $p \gets L$
    \State $L \gets $ \Call{Next}{$L$}
  \EndWhile
  \State \Call{Next}{$x$} $\gets L$
  \If{$p \neq$ NIL}                           // It should be \If{$p \eq$ NIL}, right?
    \State $H \gets x$
  \Else
    \State \Call{Next}{$p$} $\gets x$
  \EndIf
  \State \Return $H$
\EndFunction
\end{algorithmic}
```

Best Regards,

**Comment by po2xel** [comment]
And the Red-Black tree in **Figure 3.4: An example red-black tree** is not correct. The leaf (NIL)  isn't drawn as black as shown in the wiki page: https://en.wikipedia.org/wiki/File:Red-black_tree_example.svg
 It leads to confusion when I read the properties and the example shown in Figure 3.4.

**Comment by liuxinyu95** [comment]
You are right.
I updated the insertion sort algorithm with this fix:
https://github.com/liuxinyu95/AlgoXY/commit/7d9891cd0a199bb5768e48dcaf8835f38c594f58

I'll next check the red-black tree figure issue.

**Comment by liuxinyu95** [comment]
I added a figure to shown the NIL nodes, then explain the reason why we'll ignore the black NIL nodes in the rest of the book. See the following commit:
https://github.com/liuxinyu95/AlgoXY/commit/8da19de9d62751c7d512caf6ab9bb4198f62a096

Here is the sample chapter with this change.
[rbtree-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/1346036/rbtree-en.pdf)
