### ISSUE TITLE
corner case in circular buffer queue

### ISSUE THREAD

**Issue by tlxxzj** [liuxinyu95/AlgoXY#45]
if the buffer size = 1,  head and tail always 0, 
so we can't use head == tail to judge if the queue is empty,

**Comment by liuxinyu95** [comment]
Thank you to point out this error.
I considered again this problem. A better idea is to only record the head, and the count. 
1) The count can tell if the queue is empty (count == 0), or full (count == size);
2) The tail can always be calculated by tail = head + count.

Here is the updated program based on this idea:
https://github.com/liuxinyu95/AlgoXY/blob/jvm/datastruct/elementary/queue/src/queue.c#L100

I'll next updated the contents for all branches.

**Comment by liuxinyu95** [comment]
Updated in all the branches:
algoxy: English ver;
zh-cn: Chinese ver;
jvm: on-going Java/Scala examples version.
