### ISSUE TITLE
recipe for target 'others/preface/preface-en.pdf' failed

### ISSUE THREAD

**Issue by AaronConlon** [liuxinyu95/AlgoXY#47]

**Comment by liuxinyu95** [comment]
Hello, 

Could you provide more detailed information? Do you mean you can't generate the preface-en.pdf from the Makefile or TeX source? What's the error message?

**Comment by anayrat** [comment]
Hello,
I had the same error on debian. xelatex command was missing, so preface-en.pdf was not generated. That was causing an error during processing. xelatex is provided by this package : https://packages.debian.org/stretch/texlive-xetex
