### ISSUE TITLE
字符Patricia中的insert算法

### ISSUE THREAD

**Issue by xuangu** [liuxinyu95/AlgoXY#54]
```
def insert(t, key, value = None):
    if t is None:
        t = Patricia()
    node = t
    while True:
        match = False
        for k, tr in node.children.items():
            if key == k:         
                node.value = value     # 这个地方有问题吧？感觉应该是node.children[key].value = value，覆盖对应key的节点的value值，而不是本节点的value值？
                return t
            (prefix, k1, k2) = lcp(key, k)
            if prefix != "":
                match = True
                if k2 == "":
                    node = tr
                    key = k1
                    break
                else:
                    node.children[prefix] = branch(k1, Patricia(value), k2, tr)
                    del node.children[k]
                    return t
        
        if not match:
            node.children[key] = Patricia(value)
            return t

    return t
```

**Comment by liuxinyu95** [comment]
多谢指出问题。的确应该覆盖子节点的value。

对比了
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/datastruct/tree/trie/src/PrefixTree.hs#L42 
发现Functional实现部分是正确的，对应python, c++的实现有同样的问题。原因是测试没有涵盖相同key时覆盖的情形。
我稍后会修正这部分错误。

再次感谢指出！

**Comment by liuxinyu95** [comment]
Fixed this issue in Python examples: https://github.com/liuxinyu95/AlgoXY/commit/5251431b9dab54e889019af512117eed85404cc5

Will next fix the C++ example program.

**Comment by liuxinyu95** [comment]
Fixed C++ example program: https://github.com/liuxinyu95/AlgoXY/commit/c33fea1dd06f0e7f59e41786915cd9c6648471c2#diff-c8dc91342c389679746f0efe1708d61d

Will next check the TeX manuscript.

**Comment by liuxinyu95** [comment]
Fixed in TeX[EN]: https://github.com/liuxinyu95/AlgoXY/commit/2780656a8884c91e2d857e9e397f600ec91c0de0

Will next Fix this in CN version.
