### ISSUE TITLE
placeholder for release

### ISSUE THREAD

**Issue by liuxinyu95** [liuxinyu95/AlgoXY#58]
Move list to the first chapter.
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/5981934/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/5981940/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrite chapter 3 - insertion sort
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/6054339/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/6054340/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrite chapter 4 - reb-black tree
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/6253722/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/6253733/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrite chapter 5 and Appendix B - AVL tree
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/6446719/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/6446720/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrite chapter 6 - Radix Tree
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/6862228/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/6862229/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrote chapter 7 - B-tree
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/7788975/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/7788982/algoxy-en.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Rewrote chapter 8 - Binary heap
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/9402204/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/9402206/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrote chapter 9 - selection sort
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/9592775/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/9592776/algoxy-en.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Rewrote chapter 10 - binomial heap, Fibonacci heap, and pairing heap

[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/9876013/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/9876016/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrote chapter 11 - queue (list queue, circular buffer queue, paired-list queue, balance queue, realtime queue, lazy queue)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/9996590/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/9996591/algoxy-en.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Rewrote chapter 12 - sequence (binary random access list, numeric representation, paired-array sequence, concatenate-able list, and finger tree)

[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10291144/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10291142/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrote chapter 13 - quick sort and merge sort.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10419540/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10419541/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Rewrote chapter 14 (CN) - search
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10705842/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Rewrote chapter 14 - search
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10804132/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10804129/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrote ch01 - list (CN)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10832826/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrote ch01 - list, unified list and function notation
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10893521/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10893520/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Rewrote ch02 - BST
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10931150/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10931152/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrote ch03: insertion sort, ch04: red-black tree
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10947796/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10947798/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Rewrote ch05 - AVL tree, ch06 - Radix Tree
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10950330/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10950333/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Refined the overall book, as the next milestone, I'll add exercises and answers.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/10954434/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/10954457/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Added answers to the exercise of ch0: preface, ch1: list, ch2: binary search tree.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11089453/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11089454/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Added answers to the exercise of ch0, ch1, and ch2 (EN).
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11098467/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Added answers to the exercise of ch03 insert sort, ch04 red-black tree, ch05 AVL tree.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11146247/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11146249/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Added answers to the exercise in ch06 - radix tree
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11197582/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11197583/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Added answers to ch07 - ch09
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11259689/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11259691/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Added answers from ch10 - ch13
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11307746/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11307747/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Completed adding answers to all chapters.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11372438/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11372439/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Improved CN font typesettings
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11378652/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11378653/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Proofread preface.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11395580/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11395583/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Improved figure quality
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11413742/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11413743/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
50% proofread:
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11473792/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11473794/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Proofread to chapter 9.
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11632758/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11632760/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Proofread to chapter 13 (quick sort and merge sort)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/11901255/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/11901259/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Proofread complete (2nd edition)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/12481260/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/12481261/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Added preface to the 2nd edition
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/12855002/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/12855005/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Updated the title and book headers
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/13211742/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/13211747/algoxy-zh-cn.pdf)

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Added page reference to answer by the end of each exercise
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/13434940/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/13434941/algoxy-zh-cn.pdf)

**Comment by liuxinyu95** [comment]
Broke ch14 into two:
[algoxy-zh-cn.pdf](https://github.com/liuxinyu95/AlgoXY/files/14003498/algoxy-zh-cn.pdf)
[algoxy-en.pdf](https://github.com/liuxinyu95/AlgoXY/files/14003500/algoxy-en.pdf)

**Comment by liuxinyu95** [comment]
Updated with all feedback as of 12/31/2024.
[algoxy-en.pdf](https://github.com/user-attachments/files/18287890/algoxy-en.pdf)
[algoxy-zh-cn.pdf](https://github.com/user-attachments/files/18287891/algoxy-zh-cn.pdf)
