### ISSUE TITLE
疑似typo

### ISSUE THREAD

**Issue by myfreess** [liuxinyu95/AlgoXY#60]
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/datastruct/elementary/queue/queue-zh-cn.tex

```haskell
-- 824 行
next (Concat 0 _ acc) = Done acc
``` 

在这里按照上文定义似乎应该是

```
next (Concat [] acc) = Done acc
```

**Comment by liuxinyu95** [comment]
多谢指出问题，提交了一个修改：
https://github.com/liuxinyu95/AlgoXY/commit/4567814a2f72cffd0065152dda383fc2f74ff504
这部分的code和内容有些不一致了。
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/datastruct/elementary/queue/src/RealtimeQueue.hs

我稍后会进一步修改这一章。

**Comment by myfreess** [comment]
刘老师，到汇总阶段State的定义中才添加了计数器，这里还只是状态机的雏形，上文定义中的State尚无计数器，如此改动似乎不妥@liuxinyu95

**Comment by liuxinyu95** [comment]
的确如此。先保持这个issue open。我稍后修正

**Comment by liuxinyu95** [comment]
本章已重写完毕。
