### ISSUE TITLE
4.7左图的叙述有问题

### ISSUE THREAD

**Issue by douchuan** [liuxinyu95/AlgoXY#62]
Version: 0.6180339887498949

原文：

> 图4.7给出了两棵红黑树。它 们分别由序列 11, 2, 14, 1, 7, 5, 8, 4 和 1, 2, ..., 8 构建而成。

问题：
4.7左图有数字“15”，原文叙述中没有提到“15”

我用这个序列：“15, 14, 11, 2, 1, 7, 5, 4, 8” 构造出了4.7左图
[测试工具：](https://www.cs.usfca.edu/~galles/visualization/RedBlack.html)
<img width="562" alt="Screen Shot 2021-06-22 at 16 16 58" src="https://user-images.githubusercontent.com/1279128/122892816-4e696b80-d378-11eb-927d-621dedb2e5d9.png">

**Comment by liuxinyu95** [comment]
多谢，我稍后检查一下。

**Comment by liuxinyu95** [comment]
中文版输入序列少了15，英文版是对的。这个红黑树使用Okasaki的函数式算法生成的，和一般的命令式生成的结果会有差异，参见后面的图4.11。虽然不同，但它是合法的红黑树。
