### ISSUE TITLE
前言练习题 typo

### ISSUE THREAD

**Issue by hongjia** [liuxinyu95/AlgoXY#69]
Preface，练习一，第1题中：

> 之后再次扫描一遍列表，找到第一个整数所在的位置就是答案。

似应为“找到第一个**正数**所在的位置”。

**Comment by liuxinyu95** [comment]
多谢来信，你指出的问题是对的，我已经修改：https://github.com/liuxinyu95/AlgoXY/commit/e25052d6170bbf8cf86625fddef172c80fe555da
