### ISSUE TITLE
前言typo

### ISSUE THREAD

**Issue by hongjia** [liuxinyu95/AlgoXY#70]
“0.2.3 队列”节：
>如果$x$是从$Q_{23}$取出的，我们只将$3x$加入$Q_{23}$，$5x$加入$Q_{235}$。我们不应该将$2x$加入$Q_2$，因为$Q_3$中不允许包含被3整除的数。

应为：
如果$x$是从$Q_{23}$取出的，我们只将$3x$加入$Q_{23}$，$5x$加入$Q_{235}$。我们不应该将$2x$加入$Q_2$，因为**$Q_2$**中不允许包含被3整除的数。

**Comment by liuxinyu95** [comment]
非常感谢指出错误，已修改：https://github.com/liuxinyu95/AlgoXY/commit/1aa5ee925f6572ba6d29acf2680a50b948200085
