### ISSUE TITLE
typo in 1.2.5节

### ISSUE THREAD

**Issue by hongjia** [liuxinyu95/AlgoXY#71]
公式（1.7）前：

> \item 如果$Y$中仅含有一个元素$[x_n]$，则倒数第$i$个元素就是表头$x_n$；

似应为“则倒数第$i$个元素就是表头**$x_1$**；”

公式（1.7）后：

> 其中数函$slide(X, Y)$同时丢弃两个列表的头部：

“数函”应为**函数**

**Comment by liuxinyu95** [comment]
感谢指出这两处错误，已修改：https://github.com/liuxinyu95/AlgoXY/commit/4f18b0f42eab839fcdf5b8acdddd0c00989ec585
