### ISSUE TITLE
typo in 红黑树

### ISSUE THREAD

**Issue by hongjia** [liuxinyu95/AlgoXY#73]
第四章红黑树开头：

> 能否是用二叉搜索树处理通讯录，……

似应为 “能否使用二叉搜索树……”，或“是否能用二叉搜索树……”

**Comment by liuxinyu95** [comment]
多谢指出，已修改：https://github.com/liuxinyu95/AlgoXY/commit/31df3cae3e61b2a1369192dbb8f2ad10c02cba56
