### ISSUE TITLE
typo in 4.1定义

### ISSUE THREAD

**Issue by hongjia** [liuxinyu95/AlgoXY#75]
> 由于所有的NIL节点都是黑色的，我们通常将NIL节点隐藏不画出，如图\ref{fig:rbt-example-with-nil}所示。

应为：

由于所有的NIL节点都是黑色的，我们通常将NIL节点隐藏不画出，如图**\ref{fig:rbt-example}**所示。

**Comment by liuxinyu95** [comment]
多谢指出，这个问题只在中文版存在。已修改：https://github.com/liuxinyu95/AlgoXY/commit/93a2f4c2926f2ccda42705d6e8bc433b784fb9e3
