### ISSUE TITLE
Contributing Counting sort

### ISSUE THREAD

**Issue by NeamulIslamFahim** [liuxinyu95/AlgoXY#78]
I want to contribute counting sort

**Comment by liuxinyu95** [comment]
Hi,

This algorithm book is targeting to provide functional algorithm design that comparable to imperative ones. The source code along with the book is to provide the reader a reference/example implementation. If you want to contribute counting sort algorithm, please also provide the following things:

1. Full text to introduce and explain it in both functional and imperative way;
2. For example code, they should contain complete test/verification. We prefer randomized generating test data and verify the invariant of the algorithm.

Thanks
--
Xinyu
