### ISSUE TITLE
strange latex symbols showing up

### ISSUE THREAD

**Issue by void-elf** [liuxinyu95/AlgoXY#8]
I can't attach images, so here's a link: http://imgur.com/T4AtLr5

That's from section 1.2, the relevant tex file being datastruct/tree/binary-search-tree/bstree-en.tex.

This isn't the only place where I've noticed this problem.

**Comment by liuxinyu95** [comment]
I fixed this issue by adding `showstringspaces=false` to the `\lstset` environment.
