### ISSUE TITLE
想将《算法新解》重新排版，纳入到开放式结构化示例图书中

### ISSUE THREAD

**Issue by da-liii** [liuxinyu95/AlgoXY#88]
您好，我们想给[墨客实验室](https://github.com/XmacsLabs)新增一本开放式结构化图书：
1. 使用[墨干编辑器](https://mogan.app) 1.2.x以及即将实现的[tmu格式](https://github.com/XmacsLabs/tmu)（采用Unicode编码而不是Cork编码）重新排版
2. 中文和英文会在同一个文档中，我们会在墨干编辑器中提供逐行或者逐段落（这个粒度是可以由编辑器自行调整）的中英文对比阅读功能
3. 至于排版的效果希望能够强于LaTeX的排版效果（我们在排版这本书的同时，也会同时改善墨干编辑器的排版引擎）
4. 墨干编辑器会提供结构化的版本控制功能，可以很方便的查看Git提交记录的结构化差异

希望得到《算法新解》作者的支持，也希望在未来一年内，我们提供第一章（前几章）的GNU TeXmacs/墨干编辑器重新排版文档，您能够尝试一下。如果墨干编辑器的排版效果和编辑功能都能比LaTeX好，非常希望您未来能够采用墨干编辑器编写本书的后续版本。

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
多谢来信！由于资源、时间、精力有限，目前我们把重点放在本书的内容修改、扩展习题、和提供参考答案上。我们欢迎任何人和开源项目使用不同的方式呈现本书的内容。包括设备无关的电子阅读体验，选择不同语言例子代码的互动体验等等。我们也欢迎folk本书，并在开源协议下传播到其它社区。

再次感谢来信

--
刘新宇
