### ISSUE TITLE
关于1.13.6答案的除法部分

### ISSUE THREAD

**Issue by FlyCloudC** [liuxinyu95/AlgoXY#92]
首先有个typo：

`但是我们可以做得更好。考虑$as = q \cdot bs + r$，其中$q$是商，$0 \leq q < bs$是余数。`

余数那里的q应该是r

`但是我们可以做得更好。考虑$as = q \cdot bs + r$，其中$q$是商，$0 \leq r < bs$是余数。`

另外，直接看这里的形式化的描述，让我一开始有点懵，如果能事先提一下”这就是我们平时列竖式计算除法的过程“就好了。

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
非常感谢指出这个问题。我修改了typo，并且重新组织了一下描述：上来先指出带余数的除法本质上是寻找商q和余数r，使得：as = bs q + r，0<= r < b成立。对余数的限制条件要求我们先定义如何判断一个数等于0，以及两个数间的大小。
在交代完暴力解法后，提出“模仿学校课堂里学过的长除法”，我们可以不断利用as = bs q + r求出各位的q并更新r。这里不用“竖式”，而用“长除法”这个名称，是为了和英文的标准term保持一致：long division

改动已提交：
https://github.com/liuxinyu95/AlgoXY/commit/e261f5c1b685e0834043a16f935e6c1e6571af04

中文：
![image](https://github.com/liuxinyu95/AlgoXY/assets/332938/f1480744-0059-479a-be49-5e0bd6359dcf)
![image](https://github.com/liuxinyu95/AlgoXY/assets/332938/abb4dfad-6bf5-4f44-aed7-98e55b0f4f25)
英文：
![image](https://github.com/liuxinyu95/AlgoXY/assets/332938/82f0bc84-b626-4e32-a436-1ae4ceb988b3)
![image](https://github.com/liuxinyu95/AlgoXY/assets/332938/03007243-ff16-42fe-8554-61433c1af35a)
