### ISSUE TITLE
Incorrect prefix and mask in Integer prefix tree Figure 6.6(b)

### ISSUE THREAD

**Issue by hmgle** [liuxinyu95/AlgoXY#94]
Version: 2.718283

I've noticed an error in figure 6.6(b): The prefix and mask values of the last branch node(with the left sub-tree end with 12 and right sub-tree end with 15) are shown incorrectly. The correct prefix should be 1100 and the correct mask should be 100, but the current values are 1110 and 10, respectively.
![issue](https://github.com/user-attachments/assets/9a5f51ca-4e1d-4697-a788-b620139cb834)

**Comment by liuxinyu95** [comment]
Thanks for reaching out. Will look at into this.

**Comment by liuxinyu95** [comment]
Fixed: https://github.com/liuxinyu95/AlgoXY/commit/df3ec8c0daceca01c0156464783a2f549f14d8c1

**Comment by liuxinyu95** [comment]
Will take effect in PDF in the next release.
