### ISSUE TITLE
Extra \endcsname

### ISSUE THREAD

**Issue by kands-code** [liuxinyu95/AlgoXY#95]
抱歉打扰了，我最近在尝试使用 本地 Docker[^1] 编译 pdf 的时候遇到了非常多的警告（错误？）

例如：

```log
! Extra \endcsname.
\@templabel ->1.3.2thesubsection\endcsname

l.212 ...果再倒转过来（见\cref{sec:reverse}
                                                  ）。 
?
```

具体的 log 文件可以查看 [algoxy-zh-cn.log](https://github.com/user-attachments/files/18151965/algoxy-zh-cn.log)

但是编译出来的文件似乎没有问题

因为我不是很了解 LaTeX 以及 LuaLaTeX，所以我不清楚该怎么排查错误，如果需要进一步的信息，我很乐意提供

[^1]: Dockerfile 使用项目目录下 `.docker/gitpod/Dockerfile`，已使用 `apt update && apt upgrade` 和 `tlmgr update self all` 更新到最新状态，项目使用默认主分支，即 algoxy 分支

**Comment by yhzhm** [comment]
来自电子政务中心杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by liuxinyu95** [comment]
Spot check了log文件，warning属于正常现象。LaTeX在编译时会有一下几类warning：（1）第一次编译时遇到的各种引用的link会报告找不到，第二次编译时会完成所有的交叉引用。（2）多余的关闭环境的标记（3）文字折行时超出边界。等等。

**Comment by kands-code** [comment]
不过这个警告（! Extra \endcsname）需要我按下回车才会继续，不然会卡住，这个也是正常的吗？怎样才能让这个警告不会暂停编译呢？

**Comment by liuxinyu95** [comment]
多谢澄清。如果需要手工回车，这显然是个问题。我稍后尝试重现、修复。

**Comment by liuxinyu95** [comment]
我使用gitpod build一切正常，你是否用这个链接：https://gitpod.io/#https://github.com/liuxinyu95/algoxy 构建的docker？
请参考这个配置：
https://github.com/liuxinyu95/AlgoXY/blob/algoxy/.docker/gitpod/Dockerfile

```
# This is the Dockerfile for `algoxy:gitpod`.

# Debian based image from https://gitlab.com/islandoftex/images/texlive
FROM texlive/texlive:latest

USER root

RUN apt-get update && \
    apt-get install -y \
        fonts-noto-cjk fonts-freefont-ttf \
        sudo wget bash-completion && \
    apt-get clean && \
    rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod \
    # passwordless sudo for users in the 'sudo' group
    && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers

USER gitpod
WORKDIR /home/gitpod

SHELL ["/bin/bash", "-c"]

# gitpod bash prompt
RUN { echo && echo "PS1='\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]\$(__git_ps1 \" (%s)\") $ '" ; } >> .bashrc

# texlive path should be /usr/local/texlive/YYYY/bin/PLATFORM to user's PATH,
# e.g., /usr/local/texlive/2023/bin/x86_64-linux

ENV PATH="/home/gitpod/.local/bin:${PATH}"

# fix the infoview when the container is used on gitpod:
ENV VSCODE_API_VERSION="1.50.0"

# ssh to github once to bypass the unknown fingerprint warning
RUN ssh -o StrictHostKeyChecking=no github.com || true

# run sudo once to suppress usage info
RUN sudo echo finished
```

**Comment by liuxinyu95** [comment]
检查了你附上的log，发现所有这类错误后面都跟了一个乱码字符：
```
l.212 ...果再倒转过来（见\cref{sec:reverse}
                                                  ）。󿿿
```

又如：

```
l.994 ...索方法实现它（见\cref{sec:DFS-BFS}
                                                  ）：󿿿
```

Emacs显示为0FFFFF。我初步认为是换行\r\n，或者encoding之类的问题引起。建议你修改git或编辑器的编码配置试试看。

**Comment by kands-code** [comment]
嗯，感谢排查，我今晚回去后确认一下，谢谢！

**Comment by kands-code** [comment]
经过重新生成 Docker 镜像以及确认了所有文件的编码和 eol，在 Docker 中（Debian testing 环境），eol 为 lf[^1]，编码都是 utf-8，本地环境为 Linux，在编译过程中还是会遇到这个问题，关于这个字符，我尝试将可能出错的地方都替换为“正确字符”[^2]，在第二遍编译过程[^3]中还是出现了这个问题，似乎并不是文件内容问题，而是编译过程中可能是 LaTeX 宏展开的时候出现了一些替换，然后出现的问题，具体过程我就不清楚了。

[^1]: eol 由项目中的 `.gitattributes` 文件规范，都是 lf
[^2]: 即手动输入对应字符，以确保没有不可显示字符干扰
[^3]: latexmk 编译过程似乎是 lualatex -> lualatex，即先运行一次 lualatex，然后再运行一次 lualatex，所以我尝试手动运行 lualatex algoxy-zh-cn 来进行编译，第一次是只有一些常规警告，没有问题，但第二遍运行的时候就出现了 `! Extra \endcsname` 这个警告

**Comment by kands-code** [comment]
具体的过程可以参见这个视频：


https://github.com/user-attachments/assets/8059bf64-0ad3-4296-b85e-610d9b2abe06

> 由于 GitHub 限制，视频有经过了压缩，所有画面整体比较糊，抱歉

鉴于 LaTeX 第二遍编译过程一般是用于确定链接和引用[^1]，并且所有出现类似警告的地方也出现了 `\cref` 这种指令，所以可能是在生成对应引用的时候出现了一些问题

[^1]: 参考自：<https://tex.stackexchange.com/questions/35832/what-are-the-situations-where-you-have-to-compile-a-document-more-than-once>

**Comment by liuxinyu95** [comment]
已经可以在Github action workflow重现：https://github.com/liuxinyu95/AlgoXY/actions/runs/12432525606/job/34712119397

**Comment by liuxinyu95** [comment]
MacTex用TeX Live Utility upgrade后也可重现。初步认为是TeXLive升级后内部cleveref和其它变化相互存在冲突或bug。

**Comment by liuxinyu95** [comment]
确定是所有section, subsection内的label/cref出现了问题。仅仅中文版有问题，目前先将cref换成ref解决（ https://github.com/liuxinyu95/AlgoXY/commit/34699010a456fe137e56c0358d16be4314d00518 ）。后继将检查是否可通过在cn环境下用usepackage[chinese]{cleveref}解决。
